INFO:root:16
INFO:telethon.client.users:Sleeping for 19s (0:00:19) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
ERROR:root:https://t.me/vrfe23
ERROR:root:No user has "vrfe23" as username
INFO:telethon.client.users:Sleeping early for 4s (0:00:04) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 4s (0:00:04) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 4s (0:00:04) on GetFullChannelRequest flood wait
ERROR:root:https://t.me/acou699
ERROR:root:No user has "acou699" as username
INFO:telethon.client.users:Sleeping for 20s (0:00:20) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 20s (0:00:20) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 19s (0:00:19) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 19s (0:00:19) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 19s (0:00:19) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 18s (0:00:18) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 17s (0:00:17) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 17s (0:00:17) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 17s (0:00:17) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 17s (0:00:17) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 16s (0:00:16) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 16s (0:00:16) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping for 16s (0:00:16) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 15s (0:00:15) on GetFullChannelRequest flood wait
INFO:telethon.client.users:Sleeping early for 14s (0:00:14) on GetFullChannelRequest flood wait
ERROR:root:https://t.me/KY7777
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/liuhedadui
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/TG096
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/bigT_ForYOU
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/zhaop
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/hgfhgf44fds
ERROR:root:No user has "hgfhgf44fds" as username
ERROR:root:https://t.me/Huobi_RK
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/TGG88888
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/fangyuanx
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/muyingjiaoliu
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/CAI309
ERROR:root:No user has "cai309" as username
ERROR:root:https://t.me/xiaobudianqun
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/canglang009
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/dsaji92
ERROR:root:No user has "dsaji92" as username
INFO:telethon.network.connection.connection:The server closed the connection while sending
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.136:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.136:443/TcpFull complete!
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
INFO:telethon.network.connection.connection:The server closed the connection while sending
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.136:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.136:443/TcpFull complete!
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
ERROR:root:https://t.me/qianzhengyuanzhu
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/TG5956
ERROR:root:No user has "tg5956" as username
ERROR:root:https://t.me/shenmaGY
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/huaxun_ph
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/FeiDu11
ERROR:root:Nobody is using this username, or the username is unacceptable. If the latter, it must match r"[a-zA-Z][\w\d]{3,30}[a-zA-Z\d]" (caused by ResolveUsernameRequest)
ERROR:root:https://t.me/yulegaoduan
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/A8jingping
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/Xiaoyao159000
ERROR:root:The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by SendMessageRequest)
ERROR:root:https://t.me/wenan00
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:https://t.me/bwg01
ERROR:root:You can't write in this chat (caused by SendMessageRequest)
ERROR:root:susu622
ERROR:root:No user has "susu622" as username
INFO:telethon.network.connection.connection:The server closed the connection while sending
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.136:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.136:443/TcpFull complete!
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
INFO:telethon.network.connection.connection:The server closed the connection while sending
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.136:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.136:443/TcpFull complete!
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
INFO:telethon.network.connection.connection:The server closed the connection while sending
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.136:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.136:443/TcpFull complete!
WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID
